# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f1842b8f3afea3e015b2eb9a76f28b38e29abe04531723328bd577885cb10d00bb53cd9053ae84a1990581e2e9f0f99fd6ee5a0ff10ca27cc04c2fec9cc6900

test:
  secret_key_base: d45f238f164921cdc9a89db5c96f917d95c331788cfecaa33b4828f4cb050c7ec2c4803d3a6a5452c60015d35b463eac18466dd7079a8e37a6951e5ef801917e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
